name: CI
on: [push]

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install, build
        run: |
          pnpm install
          pnpm build

      - name: Run lighthouseci
        run: |
          pnpm add -g @lhci/cli@0.13.x
          lhci autorun --collect.staticDistDir=out
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
