name: Lighthouse

on:
  pull_request_target:
    branches:
      - main
    types:
      - labeled

defaults:
  run:
    # This ensures that the working directory is the root of the repository
    working-directory: ./

permissions:
  contents: read
  actions: read
  # This permission is required by `thollander/actions-comment-pull-request`
  pull-requests: write

jobs:
  lighthouse-ci:
    name: Lighthouse Report
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Add Comment to PR
        # Signal that a lighthouse run is about to start
        uses: thollander/actions-comment-pull-request@d61db783da9abefc3437960d0cce08552c7c004f # v2.4.2
        with:
          message: |
            Running Lighthouse audit...
          # Used later to edit the existing comment
          comment_tag: 'lighthouse_audit'

      - name: Capture Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@dca4940010f36d2d44caa487087a09b57939b24a # v1.3.1
        id: vercel_preview_url
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 90

      - name: Git Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          # By default Git Checkout on `pull-request-target` will checkout
          # the `default` branch of the Pull Request. We want to checkout
          # the actual branch of the Pull Request.
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Audit Preview URL with Lighthouse
        # Conduct the lighthouse audit
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@03becbfc543944dd6e7534f7ff768abb8a296826 # v10.1.0
        with:
          # Defines the settings and assertions to audit
          configPath: './.lighthouserc.json'
          # These URLS capture critical pages / site functionality.
          urls: |
            ${{ steps.vercel_preview_url.outputs.url }}/
            ${{ steps.vercel_preview_url.outputs.url }}/blog
            ${{ steps.vercel_preview_url.outputs.url }}/projects
            ${{ steps.vercel_preview_url.outputs.url }}/about
          uploadArtifacts: true # save results as a action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage

      - name: Format Lighthouse Score
        # Transform the audit results into a single, friendlier output
        id: format_lighthouse_score
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        env:
          # using env as input to our script
          # see https://github.com/actions/github-script#use-env-as-input
          LIGHTHOUSE_RESULT: ${{ steps.lighthouse_audit.outputs.manifest }}
          LIGHTHOUSE_LINKS: ${{ steps.lighthouse_audit.outputs.links }}
          VERCEL_PREVIEW_URL: ${{ steps.vercel_preview_url.outputs.url }}
        with:
          # Run as a separate file so we do not have to inline all of our formatting logic.
          # See https://github.com/actions/github-script#run-a-separate-file for more info.
          script: |
            const { formatLighthouseResults } = await import('${{github.workspace}}/scripts/lighthouse/index.mjs')
            await formatLighthouseResults({core})

      - name: Add Comment to PR
        # Replace the previous message with our formatted lighthouse results
        uses: thollander/actions-comment-pull-request@d61db783da9abefc3437960d0cce08552c7c004f # v2.4.2
        with:
          # Reference the previously created comment
          comment_tag: 'lighthouse_audit'
          message: |
            ${{ steps.format_lighthouse_score.outputs.comment }}
